# Generated by Django 4.2 on 2025-08-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telegram", "0066_wallet_wallettransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Никнейм"
                    ),
                ),
                ("balance", models.BigIntegerField(default=0, verbose_name="Баланс")),
                ("received", models.BigIntegerField(default=0, verbose_name="Принято")),
                ("active", models.BooleanField(default=True, verbose_name="Активный")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата регистрации"
                    ),
                ),
                (
                    "in_work",
                    models.BooleanField(default=False, verbose_name="В работе"),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trader",
                        to="telegram.client",
                        verbose_name="Аккаунт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Трейдер",
                "verbose_name_plural": "Трейдеры",
            },
        ),
        migrations.CreateModel(
            name="WorkingShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_shifts",
                        to="trading.trader",
                        verbose_name="Трейдер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена трейдера",
                "verbose_name_plural": "Смены трейдеров",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID заявки"
                    ),
                ),
                ("amount", models.BigIntegerField(verbose_name="Сумма")),
                (
                    "changed_amount",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Измененная сумма"
                    ),
                ),
                ("bank", models.CharField(max_length=200, verbose_name="Банк")),
                (
                    "cardholder_name",
                    models.CharField(max_length=200, verbose_name="ФИО держателя"),
                ),
                (
                    "requisites",
                    models.CharField(max_length=200, verbose_name="Реквизиты"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⚠️ В обработке"),
                            ("confirmed", "✅ Подтверждена"),
                            ("rejected", "❌ Отменена"),
                        ],
                        default="pending",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                ("closed", models.BooleanField(default=False)),
                (
                    "trader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.trader",
                        verbose_name="Трейдер",
                    ),
                ),
                (
                    "working_shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.workingshift",
                        verbose_name="Смена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
