# Generated by Django 4.2 on 2025-08-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0096_card_trader_alter_card_bank_alter_card_status"),
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardProxy",
            fields=[],
            options={
                "verbose_name": "Карта",
                "verbose_name_plural": "Карты",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("general_settings.card",),
        ),
    ]
