# Generated by Django 5.0.1 on 2024-02-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_basestats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseStats',
        ),
    ]
