# Generated by Django 5.0.1 on 2024-02-06 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_daystats_monthstats_weekstats_yearstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daystats',
            options={'verbose_name': 'Статистика за сутки', 'verbose_name_plural': '1. Сутки'},
        ),
        migrations.AlterModelOptions(
            name='monthstats',
            options={'verbose_name': 'Статистика за месяц', 'verbose_name_plural': '3. Месяц'},
        ),
        migrations.AlterModelOptions(
            name='weekstats',
            options={'verbose_name': 'Статистика за неделю', 'verbose_name_plural': '2. Неделя'},
        ),
        migrations.AlterModelOptions(
            name='yearstats',
            options={'verbose_name': 'Статистика за год', 'verbose_name_plural': '4. Год'},
        ),
        migrations.AlterField(
            model_name='issuedpayvalue',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 2, 8, 46, 173970)),
        ),
        migrations.AlterField(
            model_name='issuedrequisites',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 2, 8, 46, 173825)),
        ),
    ]
