# Generated by Django 5.0.1 on 2024-02-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_daystats_options_alter_monthstats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedpayvalue',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issuedrequisites',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
