# Generated by Django 5.0.1 on 2024-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_issuedpayvalue_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedrequisites',
            name='requisites',
            field=models.TextField(),
        ),
    ]
