# Generated by Django 5.0.1 on 2024-02-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_issuedrequisites_requisites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedrequisites',
            name='requisites',
        ),
        migrations.AddField(
            model_name='issuedrequisites',
            name='pay_value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
