# Generated by Django 5.0.1 on 2024-02-24 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_remove_issuedrequisites_requisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedrequisites',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 19, 15, 36, 471631)),
        ),
    ]
