# Generated by Django 5.0.1 on 2024-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_alter_issuedrequisites_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedrequisites',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
