# Generated by Django 5.0.1 on 2024-03-07 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_alter_issuedrequisites_datetime'),
        ('telegram', '0037_client_passed_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_value', models.IntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.client')),
            ],
        ),
    ]
