# Generated by Django 4.2.2 on 2023-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_for_order', models.PositiveIntegerField(help_text='В минутах', verbose_name='Время заявки')),
                ('auto_handler', models.BooleanField(verbose_name='Автомат')),
                ('support_contact', models.CharField(max_length=200, verbose_name='Поддержка')),
                ('boss_contact', models.CharField(max_length=200, verbose_name='Босс')),
                ('reviews_contact', models.CharField(max_length=200, verbose_name='Отзывы')),
            ],
            options={
                'verbose_name': 'Основные',
                'verbose_name_plural': 'Основные',
            },
        ),
    ]
