# Generated by Django 4.2.2 on 2023-08-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='boss_contact',
        ),
    ]
