# Generated by Django 4.2.2 on 2023-08-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0002_remove_generalsettings_boss_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='time_for_payment',
            field=models.PositiveIntegerField(default=5, help_text='В минутах', verbose_name='Время на оплату'),
            preserve_default=False,
        ),
    ]
