# Generated by Django 4.2.2 on 2023-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0003_generalsettings_time_for_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='admin_tg_id',
            field=models.BigIntegerField(default=1111, verbose_name='TG ID админа'),
            preserve_default=False,
        ),
    ]
