# Generated by Django 4.2.2 on 2023-08-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0004_generalsettings_admin_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент')),
                ('fee', models.PositiveIntegerField(default=0, help_text='s/pB', verbose_name='Комиссия сети')),
                ('auto_fee', models.BooleanField(default=True, verbose_name='Автоматическая комиссия сети')),
                ('min_value', models.PositiveIntegerField(default=500, help_text='В рублях', verbose_name='Минимальная заявка')),
                ('available', models.BooleanField(default=True, verbose_name='Включена')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
