# Generated by Django 4.2.2 on 2023-08-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0005_crypt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypt',
            new_name='CryptSettings',
        ),
    ]
