# Generated by Django 4.2.2 on 2023-08-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0006_rename_crypt_cryptsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('bank', models.CharField(choices=[('tinkoff', 'tinkoff')], max_length=50, verbose_name='Банк')),
                ('card_number', models.CharField(max_length=200, verbose_name='Номер карты')),
                ('sbp_number', models.CharField(max_length=200, verbose_name='Номер СБП')),
                ('balance', models.FloatField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
    ]
