# Generated by Django 4.2.2 on 2023-08-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0007_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200, verbose_name='TG ID канала')),
                ('oper_percent', models.PositiveIntegerField(verbose_name='Процент оператора с ручных обменов')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Касса',
            },
        ),
    ]
