# Generated by Django 4.2.2 on 2023-08-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0008_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='bank',
            field=models.CharField(choices=[('tinkoff', 'tinkoff'), ('sberbank', 'sberbank')], max_length=50, verbose_name='Банк'),
        ),
    ]
