# Generated by Django 4.2.2 on 2023-08-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0009_alter_paymentmethod_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='channel',
            field=models.BigIntegerField(verbose_name='TG ID канала'),
        ),
    ]
