# Generated by Django 4.2.2 on 2023-08-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0010_alter_cashier_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='bank',
        ),
    ]
