# Generated by Django 4.2.2 on 2023-08-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0011_remove_paymentmethod_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='min_value_first',
            field=models.PositiveIntegerField(default=1000, help_text='В рублях', verbose_name='Мин. сумма на 1 обмен'),
            preserve_default=False,
        ),
    ]
