# Generated by Django 4.2.2 on 2023-08-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0012_generalsettings_min_value_first'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='cashback_percent',
            field=models.PositiveIntegerField(default=5, verbose_name='Процент кешбэка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='min_ref_withdrawal',
            field=models.PositiveIntegerField(default=500, verbose_name='Минимальная сумма вывода реф. счета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='ref_percent',
            field=models.PositiveIntegerField(default=5, verbose_name='Процент по реф. программе'),
            preserve_default=False,
        ),
    ]
