# Generated by Django 4.2.2 on 2023-08-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0013_generalsettings_cashback_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='cashback_order_count',
            field=models.PositiveIntegerField(default=5, help_text='В бонусной заявке списывается накопленный кешбэк', verbose_name='Номер бонусной заявки'),
            preserve_default=False,
        ),
    ]
