# Generated by Django 4.2.2 on 2023-09-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0014_generalsettings_cashback_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='cashback_percent',
        ),
    ]
