# Generated by Django 4.2.2 on 2023-09-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0015_remove_generalsettings_cashback_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='cashback_order_count',
            field=models.PositiveIntegerField(help_text='Бонусная заявка без % или со скидкой 400 руб', verbose_name='Номер бонусной заявки'),
        ),
    ]
