# Generated by Django 4.2.2 on 2023-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0016_alter_generalsettings_cashback_order_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='boss_contact',
            field=models.CharField(default='test', max_length=200, verbose_name='Босс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='chat_contact',
            field=models.CharField(default='test', max_length=200, verbose_name='Чат'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='news_contact',
            field=models.CharField(default='test', max_length=200, verbose_name='Новости'),
            preserve_default=False,
        ),
    ]
