# Generated by Django 4.2.2 on 2023-09-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0017_generalsettings_boss_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='sell_crypt_contact',
            field=models.CharField(default='test', max_length=200, verbose_name='Приемка'),
            preserve_default=False,
        ),
    ]
