# Generated by Django 4.2.2 on 2023-09-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0018_generalsettings_sell_crypt_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptsettings',
            name='fix_comission',
            field=models.PositiveIntegerField(default=100, verbose_name='Фиксированная комиссия'),
        ),
        migrations.AddField(
            model_name='cryptsettings',
            name='threshold_value',
            field=models.PositiveIntegerField(default=800, help_text='Определяет % ил фикс в заявке', verbose_name='Пороговое значение'),
        ),
    ]
