# Generated by Django 4.2.2 on 2023-09-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0019_cryptsettings_fix_comission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptsettings',
            name='threshold_value',
            field=models.PositiveIntegerField(default=800, help_text='Определяет % или фикс в заявке', verbose_name='Пороговое значение'),
        ),
    ]
