# Generated by Django 4.2.2 on 2023-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0020_alter_cryptsettings_threshold_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='TG ID чата'),
        ),
    ]
