# Generated by Django 4.2.2 on 2023-09-14 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0021_generalsettings_chat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='chat_id',
            new_name='chat_tg_id',
        ),
    ]
