# Generated by Django 5.0b1 on 2023-11-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0022_rename_chat_id_generalsettings_chat_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='cashback_percent',
            field=models.FloatField(default=5, verbose_name='Процент кешбэка'),
            preserve_default=False,
        ),
    ]
