# Generated by Django 5.0b1 on 2024-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0023_generalsettings_cashback_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_name',
            field=models.CharField(default='Другой банк', max_length=200, unique=True, verbose_name='Название СБП'),
            preserve_default=False,
        ),
    ]
