# Generated by Django 5.0b1 on 2024-01-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0024_paymentmethod_sbp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_number',
            field=models.TextField(verbose_name='Номер СБП'),
        ),
    ]
