# Generated by Django 5.0b1 on 2024-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0025_alter_paymentmethod_sbp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='name_description',
            field=models.TextField(default='test', verbose_name='Описание для сбера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_description',
            field=models.TextField(default='test', verbose_name='Описание для доп. метода оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=200, verbose_name='Реквизиты сбера'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название сбера'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название доп. метода оплаты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_number',
            field=models.TextField(verbose_name='Реквизиты доп. метода оплаты'),
        ),
    ]
