# Generated by Django 5.0.1 on 2024-02-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0026_paymentmethod_name_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='cmc_api_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ CoinMarketCap'),
        ),
    ]
