# Generated by Django 5.0.1 on 2024-02-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0027_generalsettings_cmc_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='first_discount',
            field=models.PositiveIntegerField(default=0, help_text='В процентах от профита', verbose_name='Скидка на первый обмен'),
        ),
    ]
