# Generated by Django 5.0.1 on 2024-02-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0028_generalsettings_first_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.PositiveIntegerField(help_text='В рублях', verbose_name='От')),
                ('to_value', models.PositiveIntegerField(blank=True, help_text='В рублях', null=True, verbose_name='До')),
                ('percent', models.PositiveIntegerField(verbose_name='Процент')),
                ('crypt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.cryptsettings')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
