# Generated by Django 5.0.1 on 2024-02-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0029_cryptpercent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptpercent',
            name='percent',
            field=models.FloatField(verbose_name='Процент'),
        ),
    ]
