# Generated by Django 5.0.1 on 2024-02-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0030_alter_cryptpercent_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptsettings',
            name='percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Процент'),
        ),
    ]
