# Generated by Django 5.0.1 on 2024-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0031_alter_cryptsettings_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.TextField(verbose_name='Реквизиты сбера'),
        ),
    ]
