# Generated by Django 5.0.1 on 2024-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0033_alter_paymentmethod_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.TextField(verbose_name='Реквизиты сбера'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_number',
            field=models.TextField(verbose_name='Реквизиты доп. метода оплаты'),
        ),
    ]
