# Generated by Django 5.0.1 on 2024-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0034_alter_paymentmethod_card_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='name_description',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_bank',
            field=models.CharField(max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_description',
            field=models.TextField(default='test', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_name',
            field=models.CharField(default='test', max_length=200, verbose_name='Название раздела'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'Macrodroid'), ('payok', 'Payok')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_bank',
            field=models.CharField(max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'Macrodroid'), ('payok', 'Payok')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_name',
            field=models.CharField(max_length=200, verbose_name='Название раздела'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_number',
            field=models.CharField(max_length=200, null=True, verbose_name='Номер СБП'),
        ),
    ]
