# Generated by Django 5.0.1 on 2024-04-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0035_remove_paymentmethod_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер СБП'),
        ),
    ]
