# Generated by Django 5.0.1 on 2024-04-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0036_alter_paymentmethod_card_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_number',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card1_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк 1'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card1_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты 1'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card2_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк 2'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card2_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты 2'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card3_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк 3'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card3_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты 3'),
        ),
    ]
