# Generated by Django 5.0.1 on 2024-04-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0037_remove_paymentmethod_card_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='sbp_bank',
            new_name='sbp1_bank',
        ),
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='sbp_number',
            new_name='sbp1_number',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp2_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp2_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер СБП'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp3_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp3_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер СБП'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card1_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card1_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card2_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card2_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card3_bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card3_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Номер карты'),
        ),
    ]
