# Generated by Django 5.0.1 on 2024-04-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0038_rename_sbp_bank_paymentmethod_sbp1_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=200, verbose_name='Банк')),
                ('cardholder_name', models.CharField(max_length=200, verbose_name='ФИО держателя')),
                ('card_number', models.CharField(max_length=100, verbose_name='Номер карты')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('Готова к работе', 'Готова к работе'), ('Не работает', 'Не работает'), ('В блоке', 'В блоке')], default='Готова к работе', max_length=50, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
            },
        ),
    ]
