# Generated by Django 5.0.1 on 2024-04-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0039_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card1_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card1_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card2_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card2_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card3_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card3_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp1_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp1_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp2_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp2_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp3_bank',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='sbp3_number',
        ),
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(choices=[('Райффайзен', 'Райффайзен'), ('Тинькофф', 'Тинькофф'), ('Сбербанк', 'Сбербанк')], max_length=200, verbose_name='Банк'),
        ),
    ]
