# Generated by Django 5.0.1 on 2024-04-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0040_remove_paymentmethod_card1_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='cmc_api_key',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='cmc_api_key1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ CoinMarketCap 1'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='cmc_api_key2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ CoinMarketCap 2'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='cmc_api_key3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ CoinMarketCap 3'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='cmc_api_key4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ключ CoinMarketCap 4'),
        ),
    ]
