# Generated by Django 5.0.1 on 2024-04-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0041_remove_generalsettings_cmc_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(choices=[('Райффайзен', 'Райффайзен'), ('Тинькофф', 'Тинькофф'), ('Сбербанк', 'Сбербанк'), ('Уралсиб', 'Уралсиб'), ('Росбанк', 'Росбанк')], max_length=200, verbose_name='Банк'),
        ),
    ]
