# Generated by Django 5.0.1 on 2024-04-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0042_alter_card_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('worked_all', 'В работе'), ('worked_card', 'В работе (карта)'), ('worked_sbp', 'В работе (СБП)'), ('ready', 'Готова к работе'), ('not_worked', 'Не работает'), ('blocked', 'В блоке')], default='Готова к работе', max_length=50, verbose_name='Статус'),
        ),
    ]
