# Generated by Django 5.0.1 on 2024-04-30 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0045_card_count_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('worked_all', 'В работе'), ('worked_card', 'В работе (карта)'), ('worked_sbp', 'В работе (СБП)'), ('ready', 'Готова к работе'), ('not_worked', 'Не работает'), ('blocked', 'В блоке')], default='ready', max_length=50, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnover', models.FloatField(default=0, verbose_name='Пришло на карту')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало работы')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец работы')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_settings.card')),
            ],
            options={
                'verbose_name': 'Статистика карты',
                'verbose_name_plural': 'Статистика карты',
            },
        ),
    ]
