# Generated by Django 5.0.1 on 2024-04-30 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0046_alter_card_status_cardstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardstats',
            options={'ordering': ['-id'], 'verbose_name': 'Статистика карты', 'verbose_name_plural': 'Статистика карты'},
        ),
    ]
