# Generated by Django 5.0.1 on 2024-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0047_alter_cardstats_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(choices=[('Райффайзен', 'Райффайзен'), ('Тинькофф', 'Тинькофф'), ('Сбербанк', 'Сбербанк'), ('Уралсиб', 'Уралсиб'), ('Росбанк', 'Росбанк'), ('Альфабанк', 'Альфабанк'), ('Газпромбанк', 'Газпромбанк')], max_length=200, verbose_name='Банк'),
        ),
    ]
