# Generated by Django 5.0.4 on 2024-05-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0048_alter_card_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'Macrodroid'), ('payok', 'Payok'), ('xpay', 'Xpay'), ('payok-xpay', 'Payok-Xpay'), ('xpay-payok', 'Xpay-Payok')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
