# Generated by Django 5.0.4 on 2024-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0051_alter_card_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(choices=[('Райффайзен', 'Райффайзен'), ('Тинькофф', 'Тинькофф'), ('Сбербанк', 'Сбербанк'), ('Уралсиб', 'Уралсиб'), ('Росбанк', 'Росбанк'), ('Альфабанк', 'Альфабанк'), ('Газпромбанк', 'Газпромбанк'), ('Акбарс банк', 'Акбарс банк'), ('Газпром банк', 'Газпром банк'), ('Мтс банк', 'Мтс банк'), ('Отп Банк', 'Отп Банк'), ('Россельхозбанк', 'Россельхозбанк')], max_length=200, verbose_name='Банк'),
        ),
    ]
