# Generated by Django 5.0.4 on 2024-07-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0055_alter_card_bank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'permissions': [('restart_bot', 'Рестарт бота')], 'verbose_name': 'Основные', 'verbose_name_plural': 'Основные'},
        ),
    ]
