# Generated by Django 4.2 on 2024-08-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0056_alter_generalsettings_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptSellSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "percent",
                    models.PositiveIntegerField(default=10, verbose_name="Процент"),
                ),
                (
                    "min_value_sell",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="В рублях",
                        verbose_name="Минимальная заявка на продажу",
                    ),
                ),
                (
                    "threshold_value",
                    models.PositiveIntegerField(
                        default=800,
                        help_text="Определяет % или фикс в заявке",
                        verbose_name="Пороговое значение",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Включена"),
                ),
            ],
            options={
                "verbose_name": "Валюта для продажи",
                "verbose_name_plural": "Валюты для продажи",
            },
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="time_for_sell",
            field=models.PositiveIntegerField(
                default=15,
                help_text="В минутах",
                verbose_name="Время на перевод крипты",
            ),
        ),
    ]
