# Generated by Django 5.1 on 2024-08-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0057_cryptsellsettings_generalsettings_time_for_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'Macrodroid'), ('payok', 'Payok'), ('xpay', 'Xpay'), ('onlypays', 'Onlypays'), ('payok-xpay', 'Payok-Xpay'), ('xpay-payok', 'Xpay-Payok')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'Macrodroid'), ('payok', 'Payok'), ('xpay', 'Xpay'), ('onlypays', 'Onlypays'), ('payok-xpay', 'Payok-Xpay'), ('xpay-payok', 'Xpay-Payok')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
