# Generated by Django 5.0.8 on 2024-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0058_alter_paymentmethod_card_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="decrease_commission_value",
            field=models.PositiveIntegerField(
                default=0, help_text="В рублях", verbose_name="Уменьшить коммиссию на"
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="end_happy_time",
            field=models.TimeField(null=True, verbose_name="Конец счастливого часа"),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="start_happy_time",
            field=models.TimeField(null=True, verbose_name="Начало счастливого часа"),
        ),
    ]
