# Generated by Django 5.1 on 2024-08-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0059_generalsettings_decrease_commission_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='decrease_commission_value',
            field=models.PositiveIntegerField(default=0, help_text='В %', verbose_name='Уменьшить комиссию на'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='end_happy_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец счастливого часа'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='start_happy_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало счастливого часа'),
        ),
    ]
