# Generated by Django 5.0.8 on 2024-09-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0061_alter_card_bank"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="end_unhappy_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Конец несчастливого часа"
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="increase_commission_value",
            field=models.PositiveIntegerField(
                default=0, help_text="В %", verbose_name="Увеличить комиссию на"
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="start_unhappy_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Начало несчастливого часа"
            ),
        ),
    ]
