# Generated by Django 5.0.8 on 2024-09-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0062_generalsettings_end_unhappy_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(choices=[('Райффайзен', 'Райффайзен'), ('Тинькофф', 'Тинькофф'), ('Сбербанк', 'Сбербанк'), ('Уралсиб', 'Уралсиб'), ('Росбанк', 'Росбанк'), ('Альфабанк', 'Альфабанк'), ('Газпромбанк', 'Газпромбанк'), ('Акбарс банк', 'Акбарс банк'), ('Газпром банк', 'Газпром банк'), ('Мтс банк', 'Мтс банк'), ('Отп Банк', 'Отп Банк'), ('Россельхозбанк', 'Россельхозбанк'), ('УБРиР', 'УБРиР'), ('Озон банк', 'Озон банк'), ('Совкомбанк', 'Совкомбанк'), ('ВТБ', 'ВТБ'), ('Промсвязьбанк', 'Промсвязьбанк'), ('МТС Деньги (ЭКСИ Банк)', 'МТС Деньги (ЭКСИ Банк)')], max_length=200, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('macrodroid-payok', 'macrodroid-payok'), ('macrodroid-xpay', 'macrodroid-xpay'), ('macrodroid-onlypays', 'macrodroid-onlypays'), ('payok-macrodroid', 'payok-macrodroid'), ('payok', 'payok'), ('payok-xpay', 'payok-xpay'), ('payok-onlypays', 'payok-onlypays'), ('xpay-macrodroid', 'xpay-macrodroid'), ('xpay-payok', 'xpay-payok'), ('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-macrodroid', 'onlypays-macrodroid'), ('onlypays-payok', 'onlypays-payok'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('macrodroid-payok', 'macrodroid-payok'), ('macrodroid-xpay', 'macrodroid-xpay'), ('macrodroid-onlypays', 'macrodroid-onlypays'), ('payok-macrodroid', 'payok-macrodroid'), ('payok', 'payok'), ('payok-xpay', 'payok-xpay'), ('payok-onlypays', 'payok-onlypays'), ('xpay-macrodroid', 'xpay-macrodroid'), ('xpay-payok', 'xpay-payok'), ('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-macrodroid', 'onlypays-macrodroid'), ('onlypays-payok', 'onlypays-payok'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
