# Generated by Django 5.0.8 on 2024-09-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0063_alter_card_bank_alter_paymentmethod_card_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='onlypays_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Onlypays'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payok_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Payok'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='xpay_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Xpay'),
        ),
    ]
