# Generated by Django 5.0.8 on 2024-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0064_paymentmethod_onlypays_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payok_balance',
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('macrodroid-xpay', 'macrodroid-xpay'), ('macrodroid-onlypays', 'macrodroid-onlypays'), ('xpay-macrodroid', 'xpay-macrodroid'), ('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-macrodroid', 'onlypays-macrodroid'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('macrodroid-xpay', 'macrodroid-xpay'), ('macrodroid-onlypays', 'macrodroid-onlypays'), ('xpay-macrodroid', 'xpay-macrodroid'), ('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-macrodroid', 'onlypays-macrodroid'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
