# Generated by Django 5.0.8 on 2024-10-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0065_remove_paymentmethod_payok_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="reviews_tg_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="TG ID канала с отзывами"
            ),
        ),
    ]
