# Generated by Django 5.0.8 on 2024-10-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0066_generalsettings_reviews_tg_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalsettings",
            name="cashback_order_count",
            field=models.PositiveIntegerField(
                help_text="Бонусная заявка 50% или со скидкой 200 руб",
                verbose_name="Номер бонусной заявки",
            ),
        ),
    ]
