# Generated by Django 5.0.8 on 2024-10-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0067_alter_generalsettings_cashback_order_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="promo_exchange_threshold",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Кол-во обменов для использования промокода:"
            ),
        ),
    ]
