# Generated by Django 5.0.8 on 2024-10-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0068_generalsettings_promo_exchange_threshold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalsettings",
            name="promo_exchange_threshold",
        ),
    ]
