# Generated by Django 5.0.8 on 2024-10-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0069_remove_generalsettings_promo_exchange_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="decrease_cashback_value",
            field=models.PositiveIntegerField(
                default=0, help_text="В %", verbose_name="Уменьшить кешбек на"
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="increase_cashback_value",
            field=models.PositiveIntegerField(
                default=0, help_text="В %", verbose_name="Увеличить кешбек на"
            ),
        ),
    ]
