# Generated by Django 5.0.8 on 2024-11-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0070_generalsettings_decrease_cashback_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
