# Generated by Django 5.0.8 on 2024-11-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0071_alter_paymentmethod_card_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='profit_channel',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Касса чистого профита'),
        ),
    ]
