# Generated by Django 5.0.8 on 2024-11-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0072_cashier_profit_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='profit_balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс чистого профита'),
        ),
    ]
