# Generated by Django 5.0.8 on 2025-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0073_cashier_profit_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='bridgepay_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Bridgepay'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('xpay-bridgepay', 'xpay-bridgepay'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays'), ('onlypays-bridgepay', 'onlypays-bridgepay'), ('bridgepay-xpay', 'bridgepay-xpay'), ('bridgepay-onlypays', 'bridgepay-onlypays'), ('bridgepay', 'bridgepay')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('xpay', 'xpay'), ('xpay-onlypays', 'xpay-onlypays'), ('xpay-bridgepay', 'xpay-bridgepay'), ('onlypays-xpay', 'onlypays-xpay'), ('onlypays', 'onlypays'), ('onlypays-bridgepay', 'onlypays-bridgepay'), ('bridgepay-xpay', 'bridgepay-xpay'), ('bridgepay-onlypays', 'bridgepay-onlypays'), ('bridgepay', 'bridgepay')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
