# Generated by Django 5.0.8 on 2025-01-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0074_paymentmethod_bridgepay_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="add_method_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="add_method_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название раздела"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="add_method_on",
            field=models.BooleanField(default=True, verbose_name="Вкл."),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="add_method_provider",
            field=models.CharField(
                choices=[
                    ("macrodroid_tj", "macrodroid TJ"),
                    ("macrodroid_amd", "macrodroid AMD"),
                    ("bridgepay_tj", "bridgepay TJ"),
                ],
                default="macrodroid",
                max_length=50,
                verbose_name="Провайдер",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="card_on",
            field=models.BooleanField(default=True, verbose_name="Вкл."),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sbp_on",
            field=models.BooleanField(default=True, verbose_name="Вкл."),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sbp_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
    ]
