# Generated by Django 5.0.8 on 2025-01-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0075_paymentmethod_add_method_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='bridgepay_tj_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Bridgepay TJ'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='add_method_provider',
            field=models.CharField(choices=[('bridgepay_tj', 'bridgepay TJ')], default='bridgepay_tj', max_length=50, verbose_name='Провайдер'),
        ),
    ]
