# Generated by Django 5.0.8 on 2025-02-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0076_paymentmethod_bridgepay_tj_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='add_method_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('bridgepay_tj', 'bridgepay TJ')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='add_method_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('bridgepay_tj', 'bridgepay TJ')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='add_method_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('bridgepay_tj', 'bridgepay TJ')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='sbp_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
    ]
