# Generated by Django 5.0.8 on 2025-02-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0077_paymentmethod_add_method_provider_first_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='maxwealth_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Maxwealth'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('onlypays', 'onlypays'), ('maxwealth', 'maxwealth')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
    ]
