# Generated by Django 5.0.8 on 2025-03-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0078_paymentmethod_maxwealth_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="channel_news",
            field=models.CharField(
                default="", max_length=200, verbose_name="Сылка на канал новостей"
            ),
        ),
        migrations.AddField(
            model_name="generalsettings",
            name="chat_link",
            field=models.CharField(
                default="", max_length=200, verbose_name="Сылка на чат"
            ),
        ),
    ]
