# Generated by Django 5.0.8 on 2025-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0079_generalsettings_channel_news_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsettings',
            name='sell_crypt_contact',
        ),
    ]
