# Generated by Django 5.0.8 on 2025-03-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0081_alter_paymentmethod_card_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
    ]
