# Generated by Django 4.2 on 2025-06-23 00:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0082_alter_paymentmethod_card_provider_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "btc_deposit_available",
                    models.BooleanField(default=True, verbose_name="Депозит доступен"),
                ),
                (
                    "btc_withdrawal_available",
                    models.BooleanField(default=True, verbose_name="Вывод доступен"),
                ),
                (
                    "btc_withdrawal_commission",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Комиссия на вывод",
                    ),
                ),
                (
                    "btc_profit",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Профит",
                    ),
                ),
                (
                    "ltc_deposit_available",
                    models.BooleanField(default=True, verbose_name="Депозит доступен"),
                ),
                (
                    "ltc_withdrawal_available",
                    models.BooleanField(default=True, verbose_name="Вывод доступен"),
                ),
                (
                    "ltc_withdrawal_commission",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Комиссия на вывод",
                    ),
                ),
                (
                    "ltc_profit",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Профит",
                    ),
                ),
                (
                    "xmr_deposit_available",
                    models.BooleanField(default=True, verbose_name="Депозит доступен"),
                ),
                (
                    "xmr_withdrawal_available",
                    models.BooleanField(default=True, verbose_name="Вывод доступен"),
                ),
                (
                    "xmr_withdrawal_commission",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Комиссия на вывод",
                    ),
                ),
                (
                    "xmr_profit",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Профит",
                    ),
                ),
                (
                    "usdt_deposit_available",
                    models.BooleanField(default=True, verbose_name="Депозит доступен"),
                ),
                (
                    "usdt_withdrawal_available",
                    models.BooleanField(default=True, verbose_name="Вывод доступен"),
                ),
                (
                    "usdt_withdrawal_commission",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Комиссия на вывод",
                    ),
                ),
                (
                    "usdt_profit",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Профит",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки кошельков",
                "verbose_name_plural": "Настройки кошельков",
            },
        ),
        migrations.AlterField(
            model_name="generalsettings",
            name="first_discount",
            field=models.PositiveIntegerField(
                default=0, help_text="В рублях", verbose_name="Скидка на первый обмен"
            ),
        ),
    ]
