# Generated by Django 4.2 on 2025-06-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0083_walletssettings_alter_generalsettings_first_discount",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generalsettings",
            name="cashback_order_amount",
            field=models.PositiveIntegerField(
                default=0,
                help_text="В рублях",
                verbose_name="Скидка для бонусной заявки",
            ),
        ),
    ]
