# Generated by Django 4.2 on 2025-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0084_generalsettings_cashback_order_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="secrett_balance",
            field=models.IntegerField(default=0, verbose_name="Баланс Secrett"),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_provider",
            field=models.CharField(
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default="macrodroid",
                max_length=50,
                verbose_name="Провайдер",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="card_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sbp_provider",
            field=models.CharField(
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default="macrodroid",
                max_length=50,
                verbose_name="Провайдер",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sbp_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sbp_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sbp_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[("macrodroid", "macrodroid"), ("secrett", "secrett")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
    ]
