# Generated by Django 4.2 on 2025-07-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0085_paymentmethod_secrett_balance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequisitesRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(max_length=100, verbose_name="Провайдер"),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма")),
                (
                    "requisites",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Реквизиты"
                    ),
                ),
                ("success", models.BooleanField(verbose_name="Успешно")),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
                ("request_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "tg_id",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="TG ID клиента"
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос на выдачу реквизитов",
                "verbose_name_plural": "Запросы на выдачу реквизитов",
            },
        ),
    ]
