# Generated by Django 5.0.8 on 2025-08-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0090_alter_paymentmethod_card_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='bitzone_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Bitzone'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
    ]
