# Generated by Django 4.2 on 2025-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0091_paymentmethod_bitzone_balance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sbp_provider_third_reserve",
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="card_provider_fifth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 5",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="card_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sbp_provider_fifth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 5",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sbp_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
    ]
