# Generated by Django 4.2 on 2025-08-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0092_remove_paymentmethod_sbp_provider_third_reserve_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="sbp_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
    ]
