# Generated by Django 4.2 on 2025-08-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
        ("general_settings", "0095_paymentmethod_extasypay_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="trader",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="trading.trader",
                verbose_name="Трейдер",
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="bank",
            field=models.CharField(max_length=200, verbose_name="Банк"),
        ),
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[
                    ("worked_all", "В работе"),
                    ("worked_card", "В работе (карта)"),
                    ("worked_sbp", "В работе (СБП)"),
                    ("ready", "Готова к работе"),
                    ("not_worked", "Не работает"),
                    ("blocked", "В блоке"),
                    ("deleted", "Удалена"),
                ],
                default="ready",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
