# Generated by Django 4.2 on 2025-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0096_card_trader_alter_card_bank_alter_card_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="card_provider_sixth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                    ("wellbit", "wellbit"),
                    ("extasypay", "extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 6",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sbp_provider_sixth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("macrodroid", "macrodroid"),
                    ("secrett", "secrett"),
                    ("alfateam", "alfateam"),
                    ("pspware", "pspware"),
                    ("merchant001", "merchant001"),
                    ("bitzone", "bitzone"),
                    ("wellbit", "wellbit"),
                    ("extasypay", "extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 6",
            ),
        ),
    ]
