# Generated by Django 5.0.8 on 2025-08-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0097_paymentmethod_card_provider_sixth_reserve_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='infinitypay_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс Infinitypay'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_fifth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 5'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_fourth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 4'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_sixth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 6'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider',
            field=models.CharField(choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default='macrodroid', max_length=50, verbose_name='Провайдер'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_fifth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 5'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_first_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 1'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_fourth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 4'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_second_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 2'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_sixth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 6'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_third_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 3'),
        ),
    ]
