# Generated by Django 4.2 on 2025-08-30 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0098_paymentmethod_infinitypay_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название раздела"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_on",
            field=models.BooleanField(default=False, verbose_name="Вкл."),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("infinitypay", "Infinitypay"),
                    ("extasypay", "Extasypay"),
                ],
                default="merchant001",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("infinitypay", "Infinitypay"),
                    ("extasypay", "Extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("infinitypay", "Infinitypay"),
                    ("extasypay", "Extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("infinitypay", "Infinitypay"),
                    ("extasypay", "Extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("infinitypay", "Infinitypay"),
                    ("extasypay", "Extasypay"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название раздела"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_on",
            field=models.BooleanField(default=False, verbose_name="Вкл."),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_provider",
            field=models.CharField(
                choices=[("extasypay", "Extasypay")],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
