# Generated by Django 4.2 on 2025-08-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0099_paymentmethod_alfa_monobank_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_first_reserve",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_second_reserve",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_third_reserve",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sber_monobank_description",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sber_monobank_name",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sber_monobank_on",
        ),
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sber_monobank_provider",
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[("extasypay", "Extasypay")],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
