# Generated by Django 4.2 on 2025-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0100_remove_paymentmethod_alfa_monobank_provider_first_reserve_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[("extasypay", "Extasypay"), ("infinitypay", "Infinitypay")],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
