# Generated by Django 5.0.8 on 2025-08-31 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0099_paymentmethod_vita_balance_and_more'),
        ('general_settings', '0100_remove_paymentmethod_alfa_monobank_provider_first_reserve_and_more'),
    ]

    operations = [
    ]
