# Generated by Django 4.2 on 2025-09-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0101_alter_paymentmethod_alfa_monobank_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                ],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
