# Generated by Django 4.2 on 2025-09-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0103_paymentmethod_alfa_monobank_provider_first_reserve_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[("extasypay", "Extasypay"), ("pspware", "Pspware")],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sber_monobank_provider",
            field=models.CharField(
                choices=[("extasypay", "Extasypay"), ("pspware", "Pspware")],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
