# Generated by Django 4.2 on 2025-09-01 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0104_remove_paymentmethod_alfa_monobank_provider_fourth_reserve_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentmethod",
            old_name="sber_monobank_provider_fourth_reserve",
            new_name="sber_monobank_provider_first_reserve",
        ),
    ]
