# Generated by Django 4.2 on 2025-09-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0105_rename_sber_monobank_provider_fourth_reserve_paymentmethod_sber_monobank_provider_first_reserve",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentmethod",
            name="sber_monobank_provider_first_reserve",
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sber_monobank_provider",
            field=models.CharField(
                choices=[("extasypay", "Extasypay")],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
