# Generated by Django 5.0.8 on 2025-09-02 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0101_merge_20250831_2214'),
        ('general_settings', '0106_remove_paymentmethod_sber_monobank_provider_first_reserve_and_more'),
    ]

    operations = [
    ]
