# Generated by Django 5.0.8 on 2025-09-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0107_merge_20250902_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_fifth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay'), ('vita', 'vita')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 7'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_provider_sixth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay'), ('vita', 'vita')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 8'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_fifth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay'), ('vita', 'vita')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 7'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='sbp_provider_sixth_reserve',
            field=models.CharField(blank=True, choices=[('macrodroid', 'macrodroid'), ('secrett', 'secrett'), ('alfateam', 'alfateam'), ('pspware', 'pspware'), ('merchant001', 'merchant001'), ('bitzone', 'bitzone'), ('wellbit', 'wellbit'), ('extasypay', 'extasypay'), ('infinitypay', 'infinitypay'), ('vita', 'vita')], default=None, max_length=50, null=True, verbose_name='Резервный провайдер 8'),
        ),
    ]
