# Generated by Django 4.2 on 2025-09-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_settings", "0110_paymentmethod_collybus_balance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
    ]
