# Generated by Django 4.2 on 2025-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0111_paymentmethod_alfa_monobank_provider_fourth_reserve",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fifth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 5",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
    ]
