# Generated by Django 4.2 on 2025-09-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0112_paymentmethod_alfa_monobank_provider_fifth_reserve_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_seventh_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 7",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_sixth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 6",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_description",
            field=models.TextField(default="", verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_name",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название раздела"
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_on",
            field=models.BooleanField(default=False, verbose_name="Вкл."),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider",
            field=models.CharField(
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default="merchant001",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_fifth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 5",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_sixth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 6",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="ozon_monobank_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("bitzone", "Bitzone"),
                    ("pspware", "Pspware"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("pspware", "Pspware"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="sber_monobank_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("pspware", "Pspware"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider",
            field=models.CharField(
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fifth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 5",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_first_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 1",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_fourth_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 4",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_second_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 2",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="alfa_monobank_provider_third_reserve",
            field=models.CharField(
                blank=True,
                choices=[
                    ("extasypay", "Extasypay"),
                    ("infinitypay", "Infinitypay"),
                    ("merchant001", "Merchant001"),
                    ("pspware", "Pspware"),
                    ("collybus", "Collybus"),
                    ("bitzone", "Bitzone"),
                ],
                default=None,
                max_length=50,
                null=True,
                verbose_name="Резервный провайдер 3",
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="sber_monobank_provider",
            field=models.CharField(
                choices=[
                    ("extasypay", "Extasypay"),
                    ("pspware", "Pspware"),
                    ("bitzone", "Bitzone"),
                ],
                default="extasypay",
                max_length=50,
                verbose_name="Основной провайдер",
            ),
        ),
    ]
