from . import start, manage_orders, wallets, calculate, functional, ban, settings, cards, cashier, get_reqs, sell_crypt

message_handlers = {
    'Меню 🏠': start.start,
    '/start': start.start,
    'unknown_command': start.unknown_command,
    'Заявка на продажу': sell_crypt.sell_crypt,
	'Продать BTC': sell_crypt.sell_btc,
	'Продать LTC': sell_crypt.sell_ltc,
	'Продать XMR': sell_crypt.sell_xmr,
	'Продать USDT': sell_crypt.sell_usdt,
    'Баланс': wallets.get_balance,
    '💳 Балансы': functional.get_provider_balances,
    'BTC📤': wallets.send_btc,
    'LTC📤': wallets.send_ltc,
    'XMR📤': wallets.send_xmr,
    'USDT📤': wallets.send_usdt,
    '🧮': calculate.start,
    '🎞': wallets.start_history,
    'Функционал': functional.start,
    '☠️ Бан': ban.start,
    '❌ Забанить': ban.start_ban,
    '❇️ Разбанить': ban.start_unban,
    '⚙️ Настройки': settings.start,
    '💳': cards.start,
    '💸': cards.notification_history,
    'КАССА': cashier.start,
    'Перенос реферала': functional.start_ref_transfer,
    'Перенос статы': functional.start_stat_transfer,
    'Сделать вывод': functional.start_withdrawal_of_funds,
    'Вкл/выкл ночь': functional.switch_night,
    'Назначить оператора': functional.select_operator,
    'Блок': functional.start_create_duty,
    'Получить реквизиты': get_reqs.start,
    'Xpay': functional.xpay_stats,
    'Изменить баланс Xpay': functional.change_xpay_balance,
    'Обнулить баланс Xpay': functional.reset_xpay_balance,
    'Alfateam': functional.alfateam_stats,
    'Изменить баланс Alfateam': functional.change_alfateam_balance,
    'Обнулить баланс Alfateam': functional.reset_alfateam_balance,
    'Pspware': functional.pspware_stats,
    'Изменить баланс Pspware': functional.change_pspware_balance,
    'Обнулить баланс Pspware': functional.reset_pspware_balance,
    'Bridgepay': functional.bridgepay_stats,
    'Изменить баланс Bridgepay': functional.change_bridgepay_balance,
    'Обнулить баланс Bridgepay': functional.reset_bridgepay_balance,
    'Bridgepay TJ': functional.bridgepay_tj_stats,
    'Изменить баланс Bridgepay TJ': functional.change_bridgepay_tj_balance,
    'Обнулить баланс Bridgepay TJ': functional.reset_bridgepay_tj_balance,
    'Secrett': functional.secrett_stats,
    'Изменить баланс Secrett': functional.change_secrett_balance,
    'Обнулить баланс Secrett': functional.reset_secrett_balance,
    'Merchant001': functional.merchant001_stats,
    'Изменить баланс Merchant001': functional.change_merchant001_balance,
    'Обнулить баланс Merchant001': functional.reset_merchant001_balance,
    'Bitzone': functional.bitzone_stats,
    'Изменить баланс Bitzone': functional.change_bitzone_balance,
    'Обнулить баланс Bitzone': functional.reset_bitzone_balance,
    'Wellbit': functional.wellbit_stats,
    'Изменить баланс Wellbit': functional.change_wellbit_balance,
    'Обнулить баланс Wellbit': functional.reset_wellbit_balance,
    'Extasypay': functional.extasypay_stats,
    'Изменить баланс Extasypay': functional.change_extasypay_balance,
    'Обнулить баланс Extasypay': functional.reset_extasypay_balance,
    'Infinitypay': functional.infinitypay_stats,
    'Изменить баланс Infinitypay': functional.change_infinitypay_balance,
    'Обнулить баланс Infinitypay': functional.reset_infinitypay_balance,
    'Vita': functional.vita_stats,
    'Изменить баланс Vita': functional.change_vita_balance,
    'Обнулить баланс Vita': functional.reset_vita_balance,
    'Откуп': cashier.start_trading_purchase,
}

state_handlers = {
    'get_address': wallets.get_address,
    'get_value': wallets.get_value,
    'accept_send': wallets.accept_send,
    'choice_calc_crypt': calculate.choice_crypt,
    'get_calc_percent': calculate.get_percent,
    'get_calc_value': calculate.get_value,
    'choice_history_crypt': wallets.choice_history_crypt,
    'choice_history_type': wallets.choice_history_type,
    'get_ban_id': ban.get_ban_id,
    'get_unban_id': ban.get_unban_id,
    'get_fee': settings.get_fee,
    'get_requisites': cards.get_requisites,
    'get_balance': cards.get_balance,
    'get_pay_value': wallets.get_pay_value,
    'get_purchase_pay_value': wallets.get_purchase_pay_value,
    'cashier_accept_close': cashier.cashier_accept_close,
    'confirm_purchase_pay_value': wallets.confirm_purchase_pay_value,
    'get_ref_id': functional.get_ref_id,
    'get_father_id': functional.get_father_id,
    'get_prev_tg_id': functional.get_prev_tg_id,
    'get_new_tg_id': functional.get_new_tg_id,
    'get_withdrawal_purpose': functional.get_withdrawal_purpose,
    'select_withdrawal_oper': functional.select_withdrawal_oper,
    'get_withdrawal_value': functional.get_withdrawal_value,
    'select_oper': functional.select_oper_message,
    'get_duty_amount': functional.get_duty_amount,
    'get_duty_client': functional.get_duty_client,
    'get_reqs_type': get_reqs.get_reqs_type,
    'get_reqs_amount': get_reqs.get_reqs_amount,
    'get_xpay_balance': functional.get_xpay_balance,
    'get_alfateam_balance': functional.get_alfateam_balance,
    'get_pspware_balance': functional.get_pspware_balance,
    'get_bridgepay_balance': functional.get_bridgepay_balance,
    'get_bridgepay_tj_balance': functional.get_bridgepay_tj_balance,
    'get_secrett_balance': functional.get_secrett_balance,
    'get_merchant001_balance': functional.get_merchant001_balance,
    'get_bitzone_balance': functional.get_bitzone_balance,
    'get_wellbit_balance': functional.get_wellbit_balance,
    'get_extasypay_balance': functional.get_extasypay_balance,
    'get_infinitypay_balance': functional.get_infinitypay_balance,
    'get_vita_balance': functional.get_vita_balance,
    'get_client_tg_id': sell_crypt.get_client_tg_id,
    'get_card_requisites': sell_crypt.get_card_requisites,
	'get_sell_value': sell_crypt.get_value,
	'choice_sell_payment_method': sell_crypt.choice_payment_method,
	'get_sbp_requisites': sell_crypt.get_sbp_requisites,
	'accept_sell': sell_crypt.accept_sell,
	'get_bank_name': sell_crypt.get_bank_name,
    'get_trading_purchase_amount': cashier.get_trading_purchase_amount,
    'get_trading_purchase_percent': cashier.get_trading_purchase_percent
}

callback_handlers = {
    'confirm_order': manage_orders.confirm_order,
    'reject_order': manage_orders.reject_order,
    'settings': settings.start_settings,
    'settings_on': settings.settings_on,
    'settings_off': settings.settings_off,
    'settings_fee': settings.settings_fee,
    'change_requisites': cards.change_requisites,
    'change_balance': cards.change_balance,
    'confirm_notification': cards.confirm_notification,
    'select_oper': functional.select_oper_callback,
    'complete_order_sell_rec': manage_orders.complete_order_sell_rec,
    'complete_order_sell': manage_orders.complete_order_sell,
    'payment_method_sell': sell_crypt.get_payment_method,
    'select_withdrawal_oper': functional.select_withdrawal_oper_callback,
}



