# Generated by Django 4.2.2 on 2023-08-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father', models.BigIntegerField(blank=True, null=True, verbose_name='Пришел от')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='TG ID')),
                ('username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя пользователя')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кол-во обменов')),
                ('reject_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во отклоненных заявок')),
                ('cashback', models.IntegerField(default=0, verbose_name='Кешбэк')),
                ('ref_profit', models.IntegerField(default=0, verbose_name='Реферальный счет')),
                ('ref_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во рефералов')),
                ('register_date', models.DateTimeField(verbose_name='Дата регистрации')),
                ('active_promocodes', models.TextField(null=True, verbose_name='Активные промокоды')),
                ('old_promocodes', models.TextField(null=True, verbose_name='Использованные промокоды')),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('ban', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('meta', models.JSONField(verbose_name='meta')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
