# Generated by Django 4.2.2 on 2023-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meta',
            field=models.JSONField(null=True, verbose_name='meta'),
        ),
    ]
