# Generated by Django 4.2.2 on 2023-08-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_client_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='meta'),
        ),
    ]
