# Generated by Django 4.2.2 on 2023-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_client_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка')),
                ('in_fiat', models.BooleanField(default=True, verbose_name='В рублях')),
                ('one_off', models.BooleanField(default=False, verbose_name='Одноразовый')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Кол-во использований')),
                ('available', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'промокоды',
            },
        ),
    ]
