# Generated by Django 4.2.2 on 2023-08-27 21:44

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_workingshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Для админов', max_length=200, unique=True, verbose_name='Название рассылки')),
                ('message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Необязательно', null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Рассылка',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=200)),
                ('notification_type', models.CharField(max_length=200)),
                ('pay', models.FloatField()),
                ('balance', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_id', models.CharField(max_length=200, unique=True, verbose_name='Номер заявки')),
                ('summ', models.IntegerField(verbose_name='Сумма')),
                ('datetime', models.DateTimeField(verbose_name='Время создания заявки')),
                ('status', models.CharField(choices=[('✅ Выполнена', '✅ Выполнена'), ('❌ Отклонена', '❌ Отклонена'), ('⌛️ В ожидании', '⌛️ В ожидании')], default='⌛️ В ожидании', max_length=200, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заявка на вывод реф. счета',
                'verbose_name_plural': 'Заявки на вывод реф. счета',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypt', models.CharField(max_length=200, verbose_name='Валюта')),
                ('crypt_value', models.FloatField(verbose_name='Сумма')),
                ('rub_value', models.FloatField(verbose_name='Сумма в рублях')),
                ('fee', models.FloatField(verbose_name='Комиссия сети')),
                ('fee_rub', models.FloatField(verbose_name='Комиссия сети в рублях')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('tx_link', models.CharField(max_length=200, verbose_name='Ссылка на обозреватель')),
                ('pay_value', models.FloatField(default=0, verbose_name='Сумма к оплате')),
                ('ignore', models.BooleanField(default=False, verbose_name='Не учитывать в кассе')),
                ('working_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Ручная отправка',
                'verbose_name_plural': 'Ручные отправки',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=200, verbose_name='TX ID')),
                ('crypt', models.CharField(max_length=200, verbose_name='Валюта')),
                ('crypt_value', models.FloatField(verbose_name='Сумма')),
                ('rub_value', models.FloatField(verbose_name='Сумма в рублях')),
                ('pay_value', models.FloatField(blank=True, null=True, verbose_name='Стоимость')),
                ('datetime', models.DateTimeField(verbose_name='Дата закупки')),
                ('tx_link', models.CharField(max_length=200, verbose_name='Ссылка на обозреватель')),
                ('ignore', models.BooleanField(default=False, verbose_name='Не учитывать в кассе')),
                ('working_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200, unique=True, verbose_name='ID обмена')),
                ('crypt', models.CharField(max_length=200, verbose_name='Валюта')),
                ('crypt_value', models.FloatField(verbose_name='Сумма')),
                ('course', models.FloatField(verbose_name='Курс')),
                ('rub_value', models.FloatField(verbose_name='Сумма в рублях')),
                ('pay_value', models.FloatField(verbose_name='Сумма к оплате')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('payment_method', models.CharField(max_length=200, verbose_name='Метод оплаты')),
                ('requisites', models.CharField(max_length=200, verbose_name='Реквизиты')),
                ('datetime', models.DateTimeField(verbose_name='Время создания заявки')),
                ('discount', models.FloatField(default=0, verbose_name='Скидка')),
                ('promocode', models.CharField(max_length=200, null=True, verbose_name='Промокод')),
                ('status', models.CharField(default='⚠️ Ожидает подтверждения', max_length=200, verbose_name='Статус')),
                ('tx_link', models.CharField(max_length=400, null=True, verbose_name='Ссылка на обозреватель')),
                ('cashback', models.IntegerField(default=0, verbose_name='Начислено кешбэка')),
                ('bonus_order', models.BooleanField(default=False, verbose_name='Бонусная заявка')),
                ('debited_cashback', models.IntegerField(default=0, verbose_name='Списано кешбэка')),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('auto_handler', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.client', verbose_name='Клиент')),
                ('notification', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.notification')),
                ('working_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Обмен',
                'verbose_name_plural': 'Обмены',
            },
        ),
    ]
