# Generated by Django 4.2.2 on 2023-08-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_message_notification_withdrawalrequest_transaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='use_in_cashier',
            field=models.BooleanField(default=True, verbose_name='Учитывать в кассе'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='ignore',
            field=models.BooleanField(default=False, verbose_name='Игнорировать'),
        ),
    ]
