# Generated by Django 4.2.2 on 2023-08-29 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0007_purchase_use_in_cashier_alter_purchase_ignore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='ignore',
        ),
    ]
