# Generated by Django 4.2.2 on 2023-08-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0008_remove_purchase_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='use_in_cashier',
            field=models.BooleanField(default=True, verbose_name='Учитывать в кассе'),
        ),
    ]
