# Generated by Django 4.2.2 on 2023-08-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0009_transaction_use_in_cashier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='ignore',
        ),
    ]
