# Generated by Django 4.2.2 on 2023-08-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0010_remove_transaction_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fee',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='fee_rub',
            field=models.FloatField(default=0),
        ),
    ]
