# Generated by Django 4.2.2 on 2023-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0011_order_fee_order_fee_rub'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='btc_course',
            field=models.FloatField(default=0, verbose_name='Курс BTC в начале смены'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='ltc_course',
            field=models.FloatField(default=0, verbose_name='Курс LTC в начале смены'),
        ),
    ]
