# Generated by Django 4.2.2 on 2023-09-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0012_workingshift_btc_course_workingshift_ltc_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workingshift',
            old_name='btc_course',
            new_name='btc_course_start',
        ),
        migrations.RenameField(
            model_name='workingshift',
            old_name='ltc_course',
            new_name='ltc_course_start',
        ),
        migrations.AddField(
            model_name='workingshift',
            name='btc_course_end',
            field=models.FloatField(default=0, verbose_name='Курс BTC в конце смены'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='ltc_course_end',
            field=models.FloatField(default=0, verbose_name='Курс LTC в конце смены'),
        ),
    ]
