# Generated by Django 4.2.2 on 2023-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0013_rename_btc_course_workingshift_btc_course_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='order',
            name='debited_cashback',
        ),
    ]
