# Generated by Django 4.2.2 on 2023-09-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0014_remove_client_cashback_remove_order_cashback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время изменения'),
        ),
    ]
