# Generated by Django 4.2.2 on 2023-09-14 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0015_order_updated_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=500, help_text='В рублях', verbose_name='Сумма выигрыша')),
                ('from_amount', models.PositiveIntegerField(default=0, help_text='В рублях', verbose_name='Учитывать обмены от')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(verbose_name='Дата окончания')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.client', verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Конкурс',
                'verbose_name_plural': 'Конкурсы',
            },
        ),
    ]
