# Generated by Django 4.2.2 on 2023-09-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0017_alter_competition_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.client', verbose_name='Победитель'),
        ),
    ]
