# Generated by Django 4.2.2 on 2023-09-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0018_alter_competition_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.competition', verbose_name='Конкурс'),
        ),
    ]
