# Generated by Django 4.2.2 on 2023-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0019_order_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка'),
        ),
    ]
