# Generated by Django 4.2.2 on 2023-09-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0020_client_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='spin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего спина'),
        ),
    ]
