# Generated by Django 4.2.2 on 2023-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0021_client_spin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pay_value',
            field=models.FloatField(default=0, verbose_name='Стоимость'),
        ),
    ]
