# Generated by Django 4.2.2 on 2023-10-03 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0022_alter_purchase_pay_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('Закупка', 'Закупка'), ('Отправка', 'Отправка')], max_length=50, verbose_name='Тип')),
                ('rub_value', models.FloatField(verbose_name='Номинальная сумма')),
                ('pay_value', models.FloatField(verbose_name='Оплаченная сумма')),
                ('working_shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
    ]
