# Generated by Django 4.2.2 on 2023-10-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0023_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_value',
            field=models.IntegerField(verbose_name='Оплаченная сумма'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rub_value',
            field=models.IntegerField(verbose_name='Номинальная сумма'),
        ),
    ]
