# Generated by Django 4.2.2 on 2023-10-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0024_alter_bill_pay_value_alter_bill_rub_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='promocode',
            field=models.ForeignKey(blank=True, help_text='Отправляет всем, кто активировал выбранный промокод', null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.promocode', verbose_name='Промокод'),
        ),
    ]
