# Generated by Django 5.0b1 on 2023-11-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0025_message_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='xmr_course_end',
            field=models.FloatField(default=0, verbose_name='Курс XMR в конце смены'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='xmr_course_start',
            field=models.FloatField(default=0, verbose_name='Курс XMR в начале смены'),
        ),
    ]
