# Generated by Django 5.0b1 on 2023-11-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0026_workingshift_xmr_course_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cashback',
            field=models.IntegerField(default=0, verbose_name='Кешбэк'),
        ),
    ]
