# Generated by Django 5.0b1 on 2023-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0027_client_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashback',
            field=models.FloatField(default=0, verbose_name='Кешбэк'),
        ),
    ]
