# Generated by Django 5.0b1 on 2023-12-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0028_order_cashback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.FileField(blank=True, help_text='Необязательно', null=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
