# Generated by Django 5.0b1 on 2023-12-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0029_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ref_father',
            field=models.ForeignKey(blank=True, help_text='Отправляет рассылку всем рефераллам выбранного клиента', null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram.client', verbose_name='Рефовод'),
        ),
    ]
