# Generated by Django 5.0b1 on 2023-12-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0030_message_ref_father'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='usdt_course_end',
            field=models.FloatField(default=90.65, verbose_name='Курс USDT в конце смены'),
        ),
        migrations.AddField(
            model_name='workingshift',
            name='usdt_course_start',
            field=models.FloatField(default=90.65, verbose_name='Курс USDT в начале смены'),
        ),
    ]
