# Generated by Django 5.0.1 on 2024-02-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0031_workingshift_usdt_course_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('uuid', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Реферальная ссылка',
                'verbose_name_plural': 'Реферальные ссылки',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='ref_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.reflink', verbose_name='Реферальная ссылка'),
        ),
    ]
