# Generated by Django 5.0.1 on 2024-02-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0032_reflink_client_ref_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ref_percent',
            field=models.PositiveIntegerField(null=True, verbose_name='Процент по реф. программе'),
        ),
    ]
