# Generated by Django 5.0.1 on 2024-02-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0033_client_ref_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='acitve',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
