# Generated by Django 5.0.1 on 2024-02-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0034_client_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='acitve',
            new_name='active',
        ),
    ]
