# Generated by Django 5.0.1 on 2024-02-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0035_rename_acitve_client_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requisites',
            field=models.TextField(verbose_name='Реквизиты'),
        ),
    ]
