# Generated by Django 5.0.1 on 2024-02-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0036_alter_order_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passed_captcha',
            field=models.BooleanField(default=False, verbose_name='Прошел капчу'),
        ),
    ]
