# Generated by Django 5.0.1 on 2024-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0038_order_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
