# Generated by Django 5.0.1 on 2024-04-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0040_order_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Провайдер'),
        ),
    ]
