# Generated by Django 5.0.1 on 2024-04-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0041_alter_order_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='payload'),
        ),
    ]
