# Generated by Django 5.0.1 on 2024-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0042_order_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='error',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⚠️ Ожидает подтверждения'), ('confirmed', '✅ Подтверждена'), ('cancelled', '❌ Отклонена'), ('error', '🆘 Ошибка при отправке')], default='pending', max_length=200, verbose_name='Статус'),
        ),
    ]
