# Generated by Django 5.0.1 on 2024-05-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0043_order_error_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '⚠️ Ожидает подтверждения'), ('confirmed', '✅ Подтверждена'), ('cancelled', '❌ Отклонена'), ('timeouted', '⌛️ Просрочена'), ('error', '🆘 Ошибка при отправке')], default='pending', max_length=200, verbose_name='Статус'),
        ),
    ]
