# Generated by Django 4.2 on 2024-06-24 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0044_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="activated_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время активации"
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="client_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="telegram.client",
                verbose_name="Использовал",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Время создания"
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="used_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время использования"
            ),
        ),
    ]
