# Generated by Django 5.0.4 on 2024-07-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0045_promocode_activated_time_promocode_client_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='Если не указано, то рассылка будет запущена сразу же', null=True, verbose_name='Дата запуска'),
        ),
    ]
