# Generated by Django 5.0.4 on 2024-07-29 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0046_message_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200, verbose_name='Цель вывода средств')),
                ('date', models.DateTimeField(verbose_name='Дата создания заявки')),
                ('pay_value', models.FloatField(default=0, verbose_name='Сумма вывода в RUB')),
                ('working_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Вывод',
                'verbose_name_plural': 'Выводы',
            },
        ),
    ]
