# Generated by Django 5.0.4 on 2024-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0047_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingshift',
            name='night',
            field=models.BooleanField(default=False, verbose_name='Ночь'),
        ),
    ]
