# Generated by Django 5.0.4 on 2024-07-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0049_operator_workingshift_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='channel_tg_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='TG ID кассы'),
        ),
    ]
