# Generated by Django 5.0.4 on 2024-07-30 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0050_operator_channel_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='working_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='telegram.workingshift', verbose_name='Смена'),
        ),
    ]
