# Generated by Django 4.2 on 2024-08-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0051_alter_withdrawal_working_shift"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderSell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="ID обмена"
                    ),
                ),
                ("crypt", models.CharField(max_length=200, verbose_name="Валюта")),
                ("crypt_value", models.FloatField(verbose_name="Сумма в крипте")),
                (
                    "recalculated_crypt_value",
                    models.FloatField(
                        null=True, verbose_name="Пересчитанная сумма в крипте"
                    ),
                ),
                ("course", models.FloatField(verbose_name="Курс")),
                ("rub_value", models.FloatField(verbose_name="Сумма в рублях")),
                (
                    "recalculated_rub_value",
                    models.FloatField(
                        null=True, verbose_name="Пересчитанная сумма в рублях"
                    ),
                ),
                (
                    "pay_value_with_percent",
                    models.FloatField(
                        default=0, verbose_name="Итоговая сумма оплаты с процентом"
                    ),
                ),
                (
                    "recalculated_pay_value_with_percent",
                    models.FloatField(
                        null=True,
                        verbose_name="Итоговая пересчитанная сумма оплаты с процентом",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Адрес")),
                (
                    "payment_method",
                    models.CharField(max_length=200, verbose_name="Метод оплаты"),
                ),
                ("requisites", models.TextField(verbose_name="Реквизиты")),
                (
                    "datetime",
                    models.DateTimeField(verbose_name="Время создания заявки"),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время изменения"
                    ),
                ),
                (
                    "diff_payed_value",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        max_digits=20,
                        verbose_name="Разница итоговой и оплаченной суммы",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=200, null=True, verbose_name="ID транзакции"
                    ),
                ),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "⚠️ Ожидие оплаты"),
                            ("confirmed", "✅ Подтверждена"),
                            ("completed", "🚀 Выполнена"),
                            ("paid", "💸️ Оплачена"),
                            ("cancelled", "❌ Отклонена"),
                            ("timeouted", "⌛️ Просрочена"),
                            ("partially", "⚠️ Частично оплачена"),
                            ("error", "🆘 Ошибка при отправке"),
                        ],
                        default="pending",
                        max_length=200,
                        verbose_name="Статус",
                    ),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="payload")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram.client",
                        verbose_name="Клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
            },
        ),
    ]
