# Generated by Django 5.0.4 on 2024-08-10 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0052_ordersell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersell',
            name='status',
            field=models.CharField(choices=[('pending', '⚠️ Ожидание оплаты'), ('partially', '⚠️ Частично оплачена'), ('paid', '💸️ Оплачена'), ('confirmed', '✅ Подтверждена'), ('completed', '🚀 Выполнена'), ('timeouted', '⌛️ Просрочена')], default='pending', max_length=200, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Клиент')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('working_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debts', to='telegram.workingshift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Долг',
                'verbose_name_plural': 'Долги',
            },
        ),
    ]
