# Generated by Django 5.0.4 on 2024-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0053_alter_ordersell_status_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='balance',
            field=models.BigIntegerField(default=0, verbose_name='Баланс'),
        ),
    ]
