# Generated by Django 5.0.8 on 2024-08-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0054_operator_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="count_of_users",
            field=models.CharField(
                default="", max_length=200, verbose_name="Отправлено"
            ),
        ),
    ]
