# Generated by Django 5.0.8 on 2024-09-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0055_message_count_of_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='telegram.operator', verbose_name='Оператор'),
        ),
    ]
