# Generated by Django 5.0.8 on 2024-09-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0056_withdrawal_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="pin_message_check_box",
            field=models.BooleanField(default=False, verbose_name="Сделать закреп"),
        ),
    ]
