# Generated by Django 5.0.8 on 2024-10-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0058_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="max_used_value",
            field=models.PositiveIntegerField(
                default=None,
                null=True,
                verbose_name="Максимальное кол-во использований",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="used_treshold_value",
            field=models.PositiveIntegerField(
                default=None, null=True, verbose_name="Кол-во обменов для использования"
            ),
        ),
    ]
