# Generated by Django 5.0.8 on 2024-10-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0059_promocode_max_used_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="max_used_value",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Максимальное кол-во использований",
            ),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="used_treshold_value",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Кол-во обменов для использования",
            ),
        ),
    ]
