# Generated by Django 5.0.8 on 2024-10-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0060_alter_promocode_max_used_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_info",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
