# Generated by Django 5.0.8 on 2024-11-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0061_order_discount_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Дата окончания действия",
            ),
        ),
    ]
