# Generated by Django 5.0.8 on 2024-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0062_promocode_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersell',
            name='status',
            field=models.CharField(choices=[('pending', '⚠️ Ожидание оплаты'), ('partially', '⚠️ Частично оплачена (❗️ не выплачивать фиат до подтверждения)'), ('paid', '💸️ Оплачена (❗️ не выплачивать фиат до подтверждения)'), ('confirmed', '✅ Подтверждена'), ('completed', '🚀 Выполнена'), ('timeouted', '⌛️ Просрочена')], default='pending', max_length=200, verbose_name='Статус'),
        ),
    ]
