# Generated by Django 5.0.8 on 2025-01-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0063_alter_ordersell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scam',
            field=models.BooleanField(default=False, verbose_name='Скаммер'),
        ),
    ]
