# Generated by Django 5.0.8 on 2025-01-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0064_client_scam"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordersell",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "⚠️ Ожидание оплаты"),
                    (
                        "partially",
                        "⚠️ Частично оплачена (❗️ не выплачивать фиат до подтверждения)",
                    ),
                    ("paid", "💸️ Оплачена (❗️ не выплачивать фиат до подтверждения)"),
                    ("network_error", "❗️⛔️ Ошибка сети"),
                    ("confirmed", "✅ Подтверждена"),
                    ("completed", "🚀 Выполнена"),
                    ("timeouted", "⌛️ Просрочена"),
                ],
                default="pending",
                max_length=200,
                verbose_name="Статус",
            ),
        ),
    ]
