# Generated by Django 4.2 on 2025-06-23 00:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "general_settings",
            "0083_walletssettings_alter_generalsettings_first_discount",
        ),
        ("telegram", "0065_alter_ordersell_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=255, null=True, verbose_name="Адрес"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=8,
                        default=Decimal("0"),
                        max_digits=25,
                        verbose_name="Баланс",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="telegram.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "crypt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="general_settings.cryptsettings",
                        verbose_name="Валюта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кошелек",
                "verbose_name_plural": "Кошельки",
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("withdrawal", "Вывод"), ("deposit", "Депозит")],
                        max_length=50,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "internal",
                    models.BooleanField(default=False, verbose_name="Внутренняя"),
                ),
                (
                    "tx_id",
                    models.CharField(max_length=255, verbose_name="ID транзакции"),
                ),
                (
                    "explorer_link",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Ссылка на обозреватель"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Адрес")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8, max_digits=25, verbose_name="Сумма"
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=8, max_digits=25, verbose_name="Комиссия"
                    ),
                ),
                (
                    "provider_commission",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=25,
                        verbose_name="Комиссия провайдера",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="telegram.wallet",
                        verbose_name="Кошелек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
    ]
