# Generated by Django 4.2 on 2025-08-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram", "0066_wallet_wallettransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ref_value",
            field=models.FloatField(
                default=0, verbose_name="Сумма реферальных начислений"
            ),
        ),
    ]
