"""
Django settings for exchange_bot project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOCAL = bool(int(os.environ['LOCAL']))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = LOCAL

HOST = os.environ['HOST']
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', HOST.split('//')[1]]
WEBHOOK_TOKEN = os.environ['WEBHOOK_TOKEN']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'telegram',
    'general_settings',
    'log_viewer',
    'django_ckeditor_5',
    'django_rq',
    'stats',
    'trading',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'exchange_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'exchange_bot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
if LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    # DATABASES = {
    #     'default': {
    #         'ENGINE': 'django.db.backends.postgresql_psycopg2',
    #         'HOST' : os.environ['DB_HOST'],
    #         'NAME': os.environ['DB_NAME'],
    #         'USER': os.environ['DB_USER'],
    #         'PASSWORD': os.environ['DB_PASSWORD'],
    #         'PORT': os.environ['DB_PORT'],
    #     }
    # }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'HOST' : os.environ['DB_HOST'],
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'PORT': os.environ['DB_PORT'],
        }
    }

    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': f"redis://{os.environ['REDIS_USER']}:{os.environ['REDIS_PASSWORD']}@{os.environ['REDIS_HOST']}:{os.environ['REDIS_PORT']}/1",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'console': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        },
        'file': {
            'format': '[%(levelname)s] %(asctime)s %(name)s: %(message)s'
        }
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console'
        },
        'bot': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/bot.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'mailing': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/mailing.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'wallets': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/wallets.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'notifications': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/notifications.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'process_orders': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/process_orders.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'sell_crypt': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/sell_crypt.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        },
        'requisites': {
            'class': 'exchange_bot.logging.handlers.TimedRotatingFileHandler',
            'formatter': 'file',
            'filename': 'logs/requisites.log',
            'when': 'D',
            'interval': 30,
            'backupCount': 12
        }
    },
    'loggers': {
        'BOT': {
            'level': 'DEBUG',
            'handlers': ['bot', 'console']
        },
        'MAILING': {
            'level': 'DEBUG',
            'handlers': ['mailing']
        },
        'WALLETS': {
            'level': 'DEBUG',
            'handlers': ['wallets']
        },
        'NOTIFICATIONS': {
            'level': 'DEBUG',
            'handlers': ['notifications']
        },
        'PROCESS_ORDERS': {
            'level': 'DEBUG',
            'handlers': ['process_orders', 'console']
        },
        'SELL_CRYPT': {
            'level': 'DEBUG',
            'handlers': ['sell_crypt']
        },
        'REQUISITES': {
            'level': 'DEBUG',
            'handlers': ['requisites']
        }
    }
}

CKEDITOR_5_CUSTOM_CSS = 'css/admin_dark_mode_fix.css'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['|', 'bold', 'italic', 'link', 'code', 'strikethrough', 'underline'],
        'height': 'full',
        'width': 'full',
        'enterMode': 2,

    },
}

LOG_VIEWER_FILES = ['bot']
LOG_VIEWER_FILES_PATTERN = '*.log*'
LOG_VIEWER_FILES_DIR = 'logs/'
LOG_VIEWER_PAGE_LENGTH = 25
LOG_VIEWER_PATTERNS = ['[INFO]', '[DEBUG]', '[WARNING]', '[ERROR]', '[CRITICAL]']
LOG_VIEWER_EXCLUDE_TEXT_PATTERN = None
LOG_VIEWER_FILE_LIST_STYLES = '/static/css/admin_dark_mode_fix.css'
LOG_VIEWER_FILE_LIST_TITLE = "Журналы"

RQ_QUEUES = {
    'high': {
        'HOST': os.getenv('REDIS_HOST'),
        'PORT': os.getenv('REDIS_PORT'),
        'DB': 0,
        'USERNAME': '',
        'PASSWORD': os.getenv('REDIS_PASSWORD'),
        'DEFAULT_TIMEOUT': 500,
    },
    'default': {
        'HOST': os.getenv('REDIS_HOST'),
        'PORT': os.getenv('REDIS_PORT'),
        'DB': 0,
        'USERNAME': '',
        'PASSWORD': os.getenv('REDIS_PASSWORD'),
        'DEFAULT_TIMEOUT': 500,
    },
    'low': {
        'HOST': os.getenv('REDIS_HOST'),
        'PORT': os.getenv('REDIS_PORT'),
        'DB': 0,
        'USERNAME': '',
        'PASSWORD': os.getenv('REDIS_PASSWORD'),
        'DEFAULT_TIMEOUT': 500,
    },
}
RQ_SHOW_ADMIN_LINK = True
